# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TAFtoCSV
                                 A QGIS plugin
 Converte file TAF in CSV
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-05-20
        copyright            : (C) 2021 by Giulio Fattori
        email                : giulio.fattori@tin.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Giulio Fattori'
__date__ = '2021-05-20'
__copyright__ = '(C) 2021 by Giulio Fattori'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TAFtoCSV class from file TAFtoCSV.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .TAFtoCSV import TAFtoCSVPlugin
    return TAFtoCSVPlugin()
